In [133]:
import torch

In [134]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


### Basic Torch examples

In [135]:
randint = torch.randint(-100,100, (6,))
randint

tensor([-30, -74, -77,  99,  67,  70])

In [136]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.3],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.3000],
        [4.9000, 5.2000]])

In [137]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [138]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [139]:
input = torch.empty(2,3)
input

tensor([[2.3694e-38, 2.3694e-38, 2.3694e-38],
        [2.3694e-38, 2.3694e-38, 2.3694e-38]])

In [140]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [141]:
linspace = torch.linspace(start =-10,end=10,steps=5)
linspace

tensor([-10.,  -5.,   0.,   5.,  10.])

In [142]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [143]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

### Torch with CUDA

In [144]:
import numpy as np
import time

In [145]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [146]:
%%time
#time taken to execute a block: CPU times->Execution time :: Wall time -> Waiting + Execution

start_time = time.time()
#matrix op
zeors = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time-start_time
print(f"{elapsed_time:.10f}")

0.0000000000
CPU times: total: 0 ns
Wall time: 0 ns


In [147]:
'''
torch -> GPU
numpy -> CPU
'''

torch_rand1 = torch.rand(100,100, 100, 100).to(device)
torch_rand2 = torch.rand(100,100, 100, 100).to(device)

np_rand1 = torch.rand(100,100, 100, 100)
np_rand2 = torch.rand(100,100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"GPU: {elapsed_time:.10f}")

start_time = time.time()

rand = np.multiply(np_rand1,np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"CPU: {elapsed_time:.10f}")

GPU: 0.1566066742
CPU: 0.4470775127


* Multinomial : Probablity based values

In [148]:
# define a probablity tensor

prob = torch.tensor([0.1,0.9])
# 10% => 0, 90% => 1
samples = torch.multinomial(prob, num_samples=10, replacement=True)
samples

tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 1])

* Concatenate : Append tensors

In [149]:
tensor = torch.tensor([1,2,3,4,5])
out = torch.cat((tensor,torch.tensor([6])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6])

* Tril : set [row+1:] to zero for row in array

In [150]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

* Masked_fill : replace values as needed

In [151]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [152]:
# e^out[i][j]
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

* Transpose : Flip tensor shape

In [153]:
transpose = torch.exp(out).transpose(0, 1)
transpose

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [154]:
input = torch.zeros(1,2,3,4)
t = input.transpose(0,3)
t.shape

torch.Size([4, 2, 3, 1])

* Stack : append vertically

In [155]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])
tensor4 = torch.tensor([10,11,12])

stacked = torch.stack([tensor1,tensor2,tensor3,tensor4])
stacked

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

* Linear Function: nn.module

In [156]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([ 5.9201,  9.5924, -2.6588], grad_fn=<SqueezeBackward4>)


* softmax : e^i/sum(e^i)

In [157]:
import torch.nn.functional as F

input = torch.tensor([1.0,2.0,3.0])
softmax_out = F.softmax(input,dim=0)
softmax_out

tensor([0.0900, 0.2447, 0.6652])